### ISSUE TITLE
hoplon demos not working from home/launch page

### ISSUE THREAD

**Issue by kevinfish** [hoplon/demos#12]
Hi, I git clone the hoplon demos, cd into the demos-homepage directory.  Do boot development, then point my browser at localhost:8000 and I see the demos launch page.  I try clicking on each of the demos on the right hand side and I get a message "Not found :("

It would be nice if this was working so I wouldn't have to go into each one and do boot development then wait for each to come up.

**Comment by mynomoto** [comment]
Hi @kevinfish, sorry for taking that long to answer. You mean to have all the demos autocompiling? Because that would be too expensive as the project are wired to have one boot process for each one. To see the demos in action the way I would recommend is checking them on github https://hoplon.github.io/demos/demo-path and if you find something that you want to play with then going on the specific demo and running `boot development`.
HTH
